import { InfoPage, Section } from '@/app/components/InfoPage'

import { createPageMetadata } from '@/lib/seo'

export const metadata = createPageMetadata({ title: 'Privacy Policy', description: 'How Cutly handles account, license, and desktop-app data.', path: '/privacy' })

export default function PrivacyPage() {
  return <InfoPage eyebrow="LEGAL · EFFECTIVE SEPTEMBER 22, 2026" title="Privacy Policy" intro="This policy explains how Cutly handles information when you use the Cutly website, account portal, and desktop app.">
    <Section title="Information we process"><p>For accounts and licensing, Cutly processes your account identifier, email address, name when provided, license status, and limited device information such as a hashed device identifier, platform, app version, and device activity timestamps. The website uses Clerk for authentication. Licensing, short-lived sign-in, desktop-session, rate-limit, and free-trial usage records are stored in Cutly’s Turso database. Trial records include per-feature action counts and temporary request results retained for up to 24 hours to safely handle network retries.</p><p>The desktop app stores its settings, project history, and processed files locally on your device. Credentials configured in the desktop app are stored in your operating system’s credential store.</p></Section>
    <Section title="Media and AI services"><p>Cutly can process media locally. When you use a free trial AI feature before buying a license, the relevant transcript text, prompt, words selected for smart cleaning, or caption text is sent through Cutly’s server to OpenRouter for processing. Cutly does not send your source video or audio file for these trial actions. OpenRouter processes that information under its own terms and privacy policy. Cutly stores trial action counts, token usage, and estimated cost for service limits and abuse prevention; it does not keep the submitted text in its trial usage ledger. Successful generated results are temporarily retained for up to 24 hours to make safe retries possible.</p><p>After activating a license, AI features use the OpenRouter key and model you configure in the desktop app, and relevant data is sent directly from the app to that provider. Do not submit content you are not permitted to share with the applicable provider.</p></Section>
    <Section title="Why we use information"><p>We use account and device information to authenticate you, provide and enforce licenses, prevent abuse, secure the service, respond to support requests, and meet legal obligations. We do not sell personal information.</p></Section>
    <Section title="Retention and deletion"><p>You can delete your Cutly sign-in and profile from Account settings. Deletion signs out active desktop sessions and removes account-linked free-trial counts and temporary trial results. A hashed device claim may remain unlinked to the deleted account to prevent repeated trial sign-ups on the same device. License, payment, and transaction records may be retained for as long as needed to operate the service, comply with legal obligations, resolve disputes, and enforce agreements. Desktop-session tokens expire after a limited period and can also be revoked when you sign out. Locally stored files and project history remain under your control until you delete them. You may request account-data access or deletion through Cutly support; some information may need to be retained where law permits or requires it.</p></Section>
    <Section title="Security"><p>We use reasonable administrative and technical measures to protect information, including signed, short-lived desktop authentication grants and operating-system credential storage in the desktop app. No system can guarantee absolute security.</p></Section>
    <Section title="Your choices and contact"><p>You can manage your profile or delete your account from Account settings, and sign out of the desktop app. For privacy requests or questions, contact Cutly support. If you use a third-party AI, transcription, or payment service through Cutly, contact that provider for data it controls.</p></Section>
    <Section title="Changes"><p>We may update this policy as Cutly evolves. We will post the current version here and update the effective date. Continued use after an update means you accept the revised policy to the extent permitted by law.</p></Section>
  </InfoPage>
}
